name: Deploy Platform (Control Tower)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  lint:
    uses: BT-IT-Infrastructure-CloudOps/aws-workflows/.github/workflows/reusable-static-analysis.yaml@v1.0.5

  plan:
    needs: lint
    uses: BT-IT-Infrastructure-CloudOps/aws-workflows/.github/workflows/reusable-tf-plan.yaml@v1.0.5
    with:
      env_name: "prod"
    secrets:
      OIDC_ROLE_ARN: ${{ secrets.AWS_AVM_OIDC_ROLE_ARN }}
      GH_PAT: ${{ secrets.GH_PAT }}

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    uses: BT-IT-Infrastructure-CloudOps/aws-workflows/.github/workflows/reusable-tf-apply.yaml@v1.0.5
    with:
      env_name: "prod"
    secrets:
      OIDC_ROLE_ARN: ${{ secrets.AWS_AVM_OIDC_ROLE_ARN }}
      GH_PAT: ${{ secrets.GH_PAT }}